export default `email,name,surname,plusOne,delete1,group,familyName,miembroUno,miembroDos,miembroTres,miembroCuatro,miembroCinco
,Flor,,,,Familia,Flor & Guso,Guso,,,,
,Guada,,,,Familia,"Guada, Nacho & Emi",Nacho,Emi,,,
,Fede,,,,Familia,Fede & Cari,Cari,,,,
,Sere,,,,Familia,Sere & Facu,Facu,,,,
,Pedro,,,,Familia,Pedro,,,,,
,Andy,,,,Familia,Diaz Blanco,Hernan,Marta,,,
,Tomi,,,,Familia,Tomi & Bianca,Bianca,,,,
,Lucas,,,,Familia,Lucas & Angie,Angie,,,,
,Tallo,,,,Familia,Tallos,Eve,,,,
,Rosana,,,,Familia,Ro & More,More,,,,
,Rosita,,,,Familia,Rosita,,,,,
,Leo,,,,Familia,Leo & Mary,Mary,,,,
,Luli,,,,Familia,Luli & Diego,Diego,,,,
,Nora,,,,Familia,Nora & Ruben,Ruben,,,,
,Ale,,,,Familia,"Ale, Hernan, Tati & Sofi",Hernan,Tati,Sofi,,
,Gabi,,,,Familia,Gabi & Julio,Julio,,,,
,Andres,,,,Maristas,Familia Adamoli,Maria,,,,
,Diego,,,,Maristas,Familia Lennon,Asun,,,,
,Gabriela,,,,Maristas,Familia Molina,Molina,,,,
,Huevo,,,,Maristas,Huevo & Mariu,Mariu,,,,
,Enrique,,,,Maristas,Familia Flaiban,Cynthia,,,,
,Florcita,,,,Casi Familia,Florcita,,,,,
,Jorge,,,,Casi Familia,Familia Gomez,Vivi,,,,
,Fer,,,,Casi Familia,"Fer, Cali, Clari & More",Cali,Clarita,More,,
,Sole,,,,Casi Familia,"Sole, Walter, Isa & Sofi",Walter,Sofi,Isa,,
,Joaco,,,,San Lucas,Joaco & Cami,Cami,,,,
,Nico,,,,San Lucas,Nico & Pame,Pame,,,,
,Pefu,,,,San Lucas,Pefu & Tefi,Tefi,,,,
,Nacho,,,,San Lucas,Nacho & Mechi,Mechi,,,,
,Leo,,,,San Lucas,Leo & Agus ,Agus,,,,
,Guido,,,,San Lucas,Dogui,,,,,
,Santi,,,,San Lucas,Santi & Agus,Agus,,,,
,Diego,,,,Rolito,Diego & Male,Male,,,,
,Ori,,,,Rolito,Ori & Mel,Mel,,,,
,Sebastian,,,,Rolito,Seba & Vic,Vic,,,,
,Cuth,,,,Rolito,Cuth,,,,,
,Any,,,,Amigos,Any & Fer,Fer,,,,
,Pala,,,,Amigos,Pala,,,,,
,Chicho,,,,Amigos,Chicho,,,,,
,Caro,,,,Amigos,Caro ,,,,,
,Juli,,,,Amigos,Juli & Sergio,Sergio,,,,
,Sofi,,,,DH,Sofi,,,,,
,Sol,,,,DH,Sol & Alex,Alex,,,,
,Augusto,,,,DH,Augusto,,,,,
,Tomi,,,,DH,Tomi,,,,,
,Adri,,,,DH,Adri,,,,,
,Cris,,,,DH,Cris,,,,,
,Anto,,,,DH,Anto & Leo,Leo,,,,
,Ale,,,,DH,Ale ,Silvi,,,,
,Vilo,,,,UX,Vilo & Damian,Damian,,,,
,Dash,,,,UX,Dash & Fede,Fede,,,,
,Gi,,,,UX,Gi ,,,,,
,Fernando,,,,Rolito,Fer,,,,,
,Eri,,,,Casi Familia,Eri & Noe,Noe,,,,
,Sonia,,,,Casi Familia,Sonia,Invitado,,,,
,Ari,,,,DH,Ari & Sol,Sol,,,,
,Adrián,,,,Casi Familia,"Adrian, Silvia & Santino",Silvia,Santino,,,
,Lau,,,,Amigos,Lau & Alan,Alan,,,,
,Pato,,,,Amigos,Pato,,,,,
,Juan,,,,Amigos,Juan,,,,,
,Guido,,,,Amigos,Guido,,,,,`

export const dirName = import.meta.url
